# Generated by Django 5.1.2 on 2024-12-06 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Макс.символов = 300",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Макс.символов = 150",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Формат: 'ул.Сибирская, д. 92'", null=True
                    ),
                ),
                (
                    "phone",
                    models.TextField(
                        blank=True, help_text="Формат: '+7 391 256-86-49'", null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=18, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=15, max_digits=18, null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=2, null=True
                    ),
                ),
                ("people_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "is_child_friendly",
                    models.BooleanField(
                        default=True,
                        help_text="Доступно ли место для несовершеннолетних",
                    ),
                ),
                (
                    "avgprice",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Средняя цена посещения",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "additional_info",
                    models.JSONField(
                        blank=True,
                        help_text="Дополнительная информация в формате JSON",
                        null=True,
                    ),
                ),
                (
                    "visit_time",
                    models.CharField(
                        blank=True,
                        help_text="Введите время посещения в формате '00:00-00:00'",
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="places",
                        to="places.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, default="default.jpg", upload_to="images"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="places.place",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TypeEstablishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="establishments",
                        to="places.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="place",
            name="establishment",
            field=models.ManyToManyField(blank=True, to="places.typeestablishment"),
        ),
        migrations.CreateModel(
            name="TypesCuisine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuisine",
                        to="places.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="place",
            name="cuisine",
            field=models.ManyToManyField(blank=True, to="places.typescuisine"),
        ),
        migrations.CreateModel(
            name="VisitingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visittime",
                        to="places.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="place",
            name="visitingTime",
            field=models.ManyToManyField(blank=True, to="places.visitingtime"),
        ),
    ]
