# Generated by Django 5.0.2 on 2024-12-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_remove_routepoint_visit_time_routepoint_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="excerpt",
            field=models.TextField(
                blank=True,
                default="def",
                help_text="Макс.символов = 150",
                max_length=200,
                null=True,
            ),
        ),
    ]
