# Generated by Django 5.0.2 on 2024-12-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0004_route_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="description",
            field=models.CharField(
                blank=True, default="def", max_length=1024, null=True
            ),
        ),
    ]
