# Generated by Django 5.0.2 on 2024-12-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="routepoint",
            name="visit_time",
        ),
        migrations.AddField(
            model_name="routepoint",
            name="description",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="routepoint",
            name="total_time",
            field=models.IntegerField(default=0),
        ),
    ]
