# Generated by Django 5.0.2 on 2024-12-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0005_route_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="description",
            field=models.TextField(
                blank=True, default="def", max_length=1024, null=True
            ),
        ),
        migrations.AlterField(
            model_name="routepoint",
            name="description",
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
